-- Ravindu Microbanking: employee authentication database
-- PostgreSQL 15+

CREATE TABLE IF NOT EXISTS branches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(12) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  status VARCHAR(12) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS employees (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(120) NOT NULL,
  email VARCHAR(254) NOT NULL UNIQUE CHECK (email = lower(email)),
  role VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'higher_manager', 'manager', 'agent')),
  branch_id INTEGER REFERENCES branches(id),
  status VARCHAR(12) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS employee_authentication (
  employee_id INTEGER PRIMARY KEY REFERENCES employees(id) ON DELETE CASCADE,
  password_hash TEXT NOT NULL,
  failed_attempts INTEGER NOT NULL DEFAULT 0 CHECK (failed_attempts >= 0),
  locked_until TIMESTAMPTZ,
  last_login_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS employee_sessions (
  token_hash TEXT PRIMARY KEY,
  employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS employee_sessions_expiry_idx ON employee_sessions(expires_at);

CREATE TABLE IF NOT EXISTS otp_challenges (
  id TEXT PRIMARY KEY,
  employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  purpose VARCHAR(20) NOT NULL CHECK (purpose IN ('login', 'password_reset')),
  code_hash TEXT NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS otp_challenges_employee_idx ON otp_challenges(employee_id, purpose, created_at DESC);

CREATE TABLE IF NOT EXISTS authentication_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INTEGER REFERENCES employees(id) ON DELETE SET NULL,
  email VARCHAR(254) NOT NULL,
  attempt_type VARCHAR(20) NOT NULL CHECK (attempt_type IN ('login_success', 'wrong_password', 'wrong_otp', 'logout', 'unauthorized')),
  ip_address INET,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS authentication_attempts_email_idx ON authentication_attempts(email, created_at DESC);

INSERT INTO branches (id, code, name)
VALUES (1, 'COL-CEN', 'Colombo Central')
ON CONFLICT (id) DO NOTHING;

INSERT INTO employees (id, full_name, email, role, branch_id)
VALUES
  (1, 'Maya Perera', 'manager@ravindu.bank', 'manager', 1),
  (2, 'Sunil Fernando', 'higher@ravindu.bank', 'higher_manager', NULL),
  (3, 'Kavindu Jayawardena', 'admin@ravindu.bank', 'admin', NULL)
ON CONFLICT (id) DO NOTHING;

-- Demo password is "password". Replace these hashes when deploying.
INSERT INTO employee_authentication (employee_id, password_hash)
SELECT e.id, '00000000000000000000000000000000:24f3a6b16e339a4661e5ac5b4033cb2081a1bcfbb80bd7d003ddd648f8e95591a7e4b7d01d8e205395933ead35c1806b054562f3c9c1c5402e34e3c0fb6b0ce3'
FROM employees e
WHERE e.email IN ('manager@ravindu.bank', 'higher@ravindu.bank', 'admin@ravindu.bank')
ON CONFLICT (employee_id) DO NOTHING;

-- Password hashes must be generated by the application. Never store plain passwords.
-- The demo application uses password authentication in src/lib/server/auth.ts.
