'use client';

import { useState } from 'react';
import { ArrowUpRight, CircleCheck, Clock3, Pencil, Plus, Users } from 'lucide-react';
import type { Customer, ModuleProps } from '@/lib/types';
import { businessDate, date, formValues, initials, money, number } from '@/lib/format';
import { Badge, DataTable, DetailList, Field, FormModal, Metric, Modal, Notice, Panel, SectionHeading } from './ui';

export function Customers({ data, onAction }: ModuleProps) {
  const [editing, setEditing] = useState<Customer | 'new' | null>(null); const [profile, setProfile] = useState<Customer | null>(null); const [statusCustomer, setStatusCustomer] = useState<Customer | null>(null);
  const currentProfile = profile && (data.customers.find(customer => customer.id === profile.id) ?? profile);
  const selected = editing && editing !== 'new' ? editing : null;
  const isAgent = data.user.role === 'agent';
  const canEdit = (customer: Customer) => isAgent && customer.agent_id === data.user.id && customer.status === 'active';
  const canChangeStatus = (customer: Customer) => isAgent && customer.agent_id === data.user.id && ['active', 'inactive'].includes(customer.status);
  return <><SectionHeading title="Customer Management" description="Register customers, manage profiles and keep every relationship in view." action={isAgent && <button className="button button-primary" onClick={() => setEditing('new')}><Plus size={18} />Register customer</button>} />
    <div className="metrics-grid"><Metric title="Total customers" value={number(data.customers.length)} subtitle="Across your accessible branches" icon={<Users size={20} />} /><Metric title="Active customers" value={number(data.customers.filter(customer => customer.status === 'active').length)} subtitle="Approved and ready to transact" icon={<CircleCheck size={20} />} accent="green" /><Metric title="Awaiting approval" value={number(data.customers.filter(customer => customer.status === 'pending').length)} subtitle="New registrations under review" icon={<Clock3 size={20} />} accent="amber" /><Metric title="Inactive customers" value={number(data.customers.filter(customer => customer.status === 'inactive').length)} subtitle="Marked inactive in the register" icon={<Users size={20} />} accent="purple" /></div>
    <Panel title="Customer directory" subtitle="A complete view of your customer relationships"><DataTable rows={data.customers} search={customer => `${customer.full_name} ${customer.nic} ${customer.customer_number} ${customer.mobile}`} filters={[{ key: 'status', label: 'statuses', value: customer => customer.status }, { key: 'branch', label: 'branches', value: customer => customer.branch_name }]} exportName="btrust-customers.csv" columns={[
      { key: 'name', label: 'Customer', render: customer => <button className="person-cell" onClick={() => setProfile(customer)}><span className="avatar">{initials(customer.full_name)}</span><span><strong>{customer.full_name}</strong><small>{customer.customer_number}</small></span></button> },
      { key: 'nic', label: 'NIC / Contact', render: customer => <div className="stack"><span className="mono">{customer.nic}</span><small>{customer.mobile}</small></div> },
      { key: 'branch', label: 'Branch / Agent', render: customer => <div className="stack"><span>{customer.branch_name}</span><small>{customer.agent_name}</small></div> },
      { key: 'status', label: 'Status', render: customer => <Badge value={customer.status} /> },
      { key: 'balance', label: 'Savings balance', className: 'align-right', render: customer => <div className="stack"><strong>{money(customer.total_balance)}</strong><small>{customer.account_count} account{Number(customer.account_count) === 1 ? '' : 's'}</small></div> },
      { key: 'actions', label: 'Actions', render: customer => <div className="row-actions"><button className="icon-button" aria-label={`Edit ${customer.full_name}`} disabled={!canEdit(customer)} onClick={() => setEditing(customer)}><Pencil size={16} /></button><button className="icon-button" aria-label={`View ${customer.full_name}`} onClick={() => setProfile(customer)}><ArrowUpRight size={18} /></button></div> },
    ]} /></Panel>
    {editing && <FormModal title={selected ? 'Edit customer profile' : 'Register a new customer'} description="Customer details are stored securely and submitted for the appropriate review." wide onClose={() => setEditing(null)} submitLabel={selected ? 'Submit changes' : 'Submit registration'} onSubmit={async form => { const values = formValues(form); await onAction({ action: selected ? 'customer.update' : 'customer.create', ...values, ...(selected ? { id: selected.id } : {}), branch_id: Number(values.branch_id), agent_id: Number(values.agent_id) }); }}>
      <div className="field-wide"><Notice>Agents submit changes for manager approval. Check the NIC and contact details before submitting.</Notice></div>
      <Field label="Full name *"><input name="full_name" required minLength={3} maxLength={120} defaultValue={selected?.full_name} autoComplete="name" /></Field>
      <Field label="National Identity Card number *" help="12 digits, or 9 digits followed by V or X."><input name="nic" required pattern="(?:[0-9]{12}|[0-9]{9}[VvXx])" defaultValue={selected?.nic} maxLength={12} /></Field>
      <Field label="Date of birth *"><input type="date" name="date_of_birth" required max={businessDate()} defaultValue={selected?.date_of_birth?.slice(0, 10)} /></Field>
      <Field label="Mobile number *"><input type="tel" name="mobile" required pattern="[0-9+ ()-]{9,16}" maxLength={16} defaultValue={selected?.mobile} placeholder="0771234567" autoComplete="tel" /></Field>
      <Field label="Email address"><input type="email" name="email" defaultValue={selected?.email} maxLength={160} autoComplete="email" /></Field>
      <Field label="Landline"><input type="tel" name="landline" pattern="[0-9+ ()-]{9,16}" maxLength={16} defaultValue={selected?.landline} /></Field>
      <Field label="Residential address *" wide><textarea name="address" required minLength={5} maxLength={400} defaultValue={selected?.address} rows={2} autoComplete="street-address" /></Field>
      <Field label="Branch *"><select name="branch_id" required defaultValue={selected?.branch_id ?? data.user.branch_id ?? ''}>{data.branches.filter(branch => branch.id === data.user.branch_id).map(branch => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></Field>
      <Field label="Assigned agent *"><select name="agent_id" required defaultValue={selected?.agent_id ?? (data.user.role === 'agent' ? data.user.id : '')}><option value="">Select an agent</option>{data.staff.filter(staff => staff.id === data.user.id).map(staff => <option key={staff.id} value={staff.id}>{staff.full_name}{staff.branch_name ? ` · ${staff.branch_name}` : ''}</option>)}</select></Field>
    </FormModal>}
    {currentProfile && <Modal title="Customer profile" onClose={() => setProfile(null)} wide><div className="modal-body"><div className="profile-heading"><span className="avatar avatar-large">{initials(currentProfile.full_name)}</span><div><h2>{currentProfile.full_name}</h2><p className="muted mono">{currentProfile.customer_number} · {currentProfile.nic}</p></div><Badge value={currentProfile.status} /></div><DetailList items={[
      ['Date of birth', date(currentProfile.date_of_birth)], ['Mobile', currentProfile.mobile], ['Email', currentProfile.email], ['Landline', currentProfile.landline], ['Address', currentProfile.address], ['Branch', currentProfile.branch_name], ['Assigned agent', currentProfile.agent_name], ['Registered', date(currentProfile.created_at)], ['Savings accounts', currentProfile.account_count], ['Total savings balance', money(currentProfile.total_balance)],
    ]} /><h3 className="subheading">Linked savings accounts</h3><div className="mini-records">{data.accounts.filter(account => account.owner_ids?.includes(currentProfile.id) || account.customer_id === currentProfile.id).map(account => <div key={account.id}><span className="mono">{account.account_number}</span><Badge value={account.status} /><strong>{money(account.balance)}</strong></div>)}{!Number(currentProfile.account_count) && <p className="muted">No savings accounts linked yet.</p>}</div></div><div className="modal-footer"><button className="button button-secondary" disabled={!canChangeStatus(currentProfile)} onClick={() => { setProfile(null); setStatusCustomer(currentProfile); }}>Request status change</button><button className="button button-primary" disabled={!canEdit(currentProfile)} onClick={() => { setProfile(null); setEditing(currentProfile); }}><Pencil size={16} />Edit profile</button></div></Modal>}
    {statusCustomer && <FormModal title="Request a status change" description={statusCustomer.full_name} onClose={() => setStatusCustomer(null)} submitLabel="Submit request" onSubmit={async form => { await onAction({ action: 'customer.status', id: statusCustomer.id, ...formValues(form) }); }}><Field label="New status *" wide><select name="status" required defaultValue=""><option value="" disabled>Select a status</option>{['active', 'inactive'].filter(status => status !== statusCustomer.status).map(status => <option key={status} value={status}>{status[0].toUpperCase() + status.slice(1)}</option>)}</select></Field><Field label="Reason *" wide><textarea name="reason" required minLength={5} maxLength={300} rows={3} /></Field></FormModal>}
  </>;
}
