-- Canonical MySQL installation entry point: npm run db:setup
-- Supply dedicated MIGRATION_DB_* credentials for the selected database.
-- Schema definitions are versioned in database/migrations/001-auth.sql,
-- 002-banking.sql, and 003-integrity.sql; explicit incremental column upgrades
-- are in scripts/migrate-database.mjs. The runner records checksums and DDL progress.
-- Do not execute historical dumps or seed scripts as schema migrations.
-- The previous destructive dump is retained in history/mysql-dump-before-integration.sql.
