-- TEST FIXTURE ONLY: recovered original banking schema, for isolated PGlite tests.
-- This is not the team's MySQL schema or an application migration.
-- BTrust MIMS / PostgreSQL 15+
-- The schema is intentionally plain SQL: each business entity has one table,
-- joint ownership uses a junction table, and financial history is append-only.
-- Money is NUMERIC, never FLOAT. Application code passes amounts as strings.

CREATE TABLE IF NOT EXISTS branches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(12) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  address TEXT NOT NULL,
  phone VARCHAR(20) NOT NULL,
  email VARCHAR(254),
  status VARCHAR(12) NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS staff (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(120) NOT NULL,
  email VARCHAR(254) NOT NULL UNIQUE CHECK (email = lower(email)),
  password_hash TEXT NOT NULL,
  role VARCHAR(20) NOT NULL CHECK (role IN ('admin','higher_manager','manager','agent')),
  branch_id INTEGER REFERENCES branches(id),
  status VARCHAR(12) NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (role IN ('admin','higher_manager') OR branch_id IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS customers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_number VARCHAR(24) NOT NULL UNIQUE,
  full_name VARCHAR(120) NOT NULL,
  nic VARCHAR(12) NOT NULL UNIQUE,
  date_of_birth DATE NOT NULL,
  address TEXT NOT NULL,
  mobile VARCHAR(20) NOT NULL,
  landline VARCHAR(20),
  email VARCHAR(254),
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  agent_id INTEGER NOT NULL REFERENCES staff(id),
  status VARCHAR(12) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','active','inactive','rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rates (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product VARCHAR(12) NOT NULL CHECK (product IN ('savings','fixed')),
  name VARCHAR(80) NOT NULL,
  term_months INTEGER NOT NULL DEFAULT 0 CHECK (term_months BETWEEN 0 AND 120),
  annual_rate NUMERIC(6,3) NOT NULL CHECK (annual_rate BETWEEN 0 AND 100),
  minimum_balance NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (minimum_balance >= 0),
  min_age INTEGER NOT NULL DEFAULT 0 CHECK (min_age BETWEEN 0 AND 120),
  max_age INTEGER NOT NULL DEFAULT 120 CHECK (max_age BETWEEN min_age AND 150),
  UNIQUE(name),
  CHECK ((product = 'savings' AND term_months = 0) OR (product = 'fixed' AND term_months > 0))
);
-- Saving interest follows the rate effective on each day. A fixed deposit keeps
-- its contracted rate until renewal, even when an administrator changes rates.
CREATE TABLE IF NOT EXISTS rate_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rate_id INTEGER NOT NULL REFERENCES rates(id),
  annual_rate NUMERIC(6,3) NOT NULL CHECK (annual_rate BETWEEN 0 AND 100),
  effective_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  changed_by INTEGER REFERENCES staff(id)
);
CREATE INDEX IF NOT EXISTS rate_history_lookup_idx ON rate_history(rate_id,effective_at DESC);

CREATE TABLE IF NOT EXISTS savings_accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_number VARCHAR(24) NOT NULL UNIQUE,
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  agent_id INTEGER NOT NULL REFERENCES staff(id),
  rate_id INTEGER NOT NULL REFERENCES rates(id),
  balance NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (balance >= 0),
  minimum_balance NUMERIC(14,2) NOT NULL DEFAULT 500 CHECK (minimum_balance >= 0),
  status VARCHAR(12) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','active','inactive','closed','rejected')),
  opened_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  closed_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS customer_accounts (
  customer_id INTEGER NOT NULL REFERENCES customers(id),
  account_id INTEGER NOT NULL REFERENCES savings_accounts(id),
  PRIMARY KEY(customer_id,account_id)
);

CREATE TABLE IF NOT EXISTS fixed_deposits (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fd_number VARCHAR(24) NOT NULL UNIQUE,
  source_account_id INTEGER NOT NULL REFERENCES savings_accounts(id),
  rate_id INTEGER NOT NULL REFERENCES rates(id),
  principal NUMERIC(14,2) NOT NULL CHECK (principal > 0),
  annual_rate NUMERIC(6,3) NOT NULL CHECK (annual_rate BETWEEN 0 AND 100),
  term_months INTEGER NOT NULL CHECK (term_months BETWEEN 1 AND 120),
  auto_renew BOOLEAN NOT NULL DEFAULT false,
  status VARCHAR(12) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','active','closed','rejected')),
  opened_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  maturity_date DATE NOT NULL,
  payout_date DATE,
  renewed_from_id INTEGER UNIQUE REFERENCES fixed_deposits(id),
  closed_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX IF NOT EXISTS one_live_fd_per_account ON fixed_deposits(source_account_id)
  WHERE status IN ('pending','active');

CREATE TABLE IF NOT EXISTS approvals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type VARCHAR(30) NOT NULL,
  entity_id INTEGER,
  branch_id INTEGER REFERENCES branches(id),
  customer_name TEXT NOT NULL DEFAULT '',
  summary TEXT NOT NULL,
  payload JSONB NOT NULL,
  requested_by INTEGER NOT NULL REFERENCES staff(id),
  status VARCHAR(12) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  reviewed_by INTEGER REFERENCES staff(id),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_at TIMESTAMPTZ,
  CHECK (requested_by <> reviewed_by),
  CHECK ((status = 'pending' AND reviewed_by IS NULL) OR (status <> 'pending' AND reviewed_by IS NOT NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS one_pending_entity_change ON approvals(type,entity_id)
  WHERE status='pending' AND entity_id IS NOT NULL;

-- A money operation groups one or two ledger entries. The actor/key pair means
-- retrying a HTTP request cannot debit or credit money twice.
CREATE TABLE IF NOT EXISTS money_operations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference VARCHAR(40) NOT NULL UNIQUE,
  actor_id INTEGER NOT NULL REFERENCES staff(id),
  idempotency_key VARCHAR(100) NOT NULL,
  request_fingerprint TEXT NOT NULL,
  type VARCHAR(30) NOT NULL,
  description VARCHAR(300) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(actor_id,idempotency_key)
);
CREATE TABLE IF NOT EXISTS ledger_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_id INTEGER NOT NULL REFERENCES money_operations(id),
  account_id INTEGER NOT NULL REFERENCES savings_accounts(id),
  type VARCHAR(30) NOT NULL,
  amount NUMERIC(14,2) NOT NULL CHECK (amount <> 0),
  balance_before NUMERIC(14,2) NOT NULL CHECK (balance_before >= 0),
  balance_after NUMERIC(14,2) NOT NULL CHECK (balance_after >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (balance_after = balance_before + amount),
  UNIQUE(operation_id,account_id)
);
CREATE INDEX IF NOT EXISTS ledger_account_date_idx ON ledger_entries(account_id,created_at,id);

CREATE TABLE IF NOT EXISTS interest_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period CHAR(7) NOT NULL CHECK (period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  branch_id INTEGER REFERENCES branches(id),
  account_count INTEGER NOT NULL DEFAULT 0,
  total_interest NUMERIC(14,2) NOT NULL DEFAULT 0,
  created_by INTEGER NOT NULL REFERENCES staff(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS interest_run_scope_month ON interest_runs(period,COALESCE(branch_id,0));
CREATE TABLE IF NOT EXISTS interest_credits (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id INTEGER NOT NULL REFERENCES interest_runs(id),
  account_id INTEGER NOT NULL REFERENCES savings_accounts(id),
  fixed_deposit_id INTEGER REFERENCES fixed_deposits(id),
  period CHAR(7) NOT NULL,
  amount NUMERIC(14,2) NOT NULL CHECK (amount >= 0),
  operation_id INTEGER REFERENCES money_operations(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS savings_interest_once ON interest_credits(account_id,period)
  WHERE fixed_deposit_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS fd_interest_once ON interest_credits(fixed_deposit_id,period)
  WHERE fixed_deposit_id IS NOT NULL;

-- Keep the daily calculation visible for the database viva and reconciliation.
-- Extra decimal places preserve sub-cent accruals; round only the monthly sum.
CREATE TABLE IF NOT EXISTS interest_accruals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INTEGER NOT NULL REFERENCES savings_accounts(id),
  accrual_date DATE NOT NULL,
  minimum_balance NUMERIC(14,2) NOT NULL CHECK (minimum_balance >= 0),
  annual_rate NUMERIC(6,3) NOT NULL,
  amount NUMERIC(18,8) NOT NULL CHECK (amount >= 0),
  UNIQUE(account_id,accrual_date)
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id INTEGER REFERENCES staff(id),
  action VARCHAR(60) NOT NULL,
  entity_type VARCHAR(30) NOT NULL,
  entity_id INTEGER,
  branch_id INTEGER REFERENCES branches(id),
  details JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS customers_branch_agent_idx ON customers(branch_id,agent_id);
CREATE INDEX IF NOT EXISTS accounts_branch_idx ON savings_accounts(branch_id);
CREATE INDEX IF NOT EXISTS approvals_queue_idx ON approvals(branch_id,status,created_at);
CREATE INDEX IF NOT EXISTS audit_branch_date_idx ON audit_logs(branch_id,created_at DESC);

CREATE OR REPLACE FUNCTION prevent_history_rewrite() RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'Financial and audit history is append-only; record a new correcting operation.';
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS ledger_immutable ON ledger_entries;
CREATE TRIGGER ledger_immutable BEFORE UPDATE OR DELETE ON ledger_entries
  FOR EACH ROW EXECUTE FUNCTION prevent_history_rewrite();
DROP TRIGGER IF EXISTS operations_immutable ON money_operations;
CREATE TRIGGER operations_immutable BEFORE UPDATE OR DELETE ON money_operations
  FOR EACH ROW EXECUTE FUNCTION prevent_history_rewrite();
DROP TRIGGER IF EXISTS audit_immutable ON audit_logs;
CREATE TRIGGER audit_immutable BEFORE UPDATE OR DELETE ON audit_logs
  FOR EACH ROW EXECUTE FUNCTION prevent_history_rewrite();
DROP TRIGGER IF EXISTS rate_history_immutable ON rate_history;
CREATE TRIGGER rate_history_immutable BEFORE UPDATE OR DELETE ON rate_history
  FOR EACH ROW EXECUTE FUNCTION prevent_history_rewrite();

-- A deferred constraint is checked at COMMIT, after the balance update AND its
-- ledger insert. Either both agree, or PostgreSQL rolls back the whole operation.
CREATE OR REPLACE FUNCTION check_account_reconciliation() RETURNS TRIGGER AS $$
DECLARE
  checked_account INTEGER;
  stored_balance NUMERIC(14,2);
  ledger_balance NUMERIC(14,2);
BEGIN
  IF TG_TABLE_NAME = 'savings_accounts' THEN
    checked_account := NEW.id;
  ELSE
    checked_account := NEW.account_id;
  END IF;
  SELECT balance INTO stored_balance FROM savings_accounts WHERE id=checked_account;
  SELECT COALESCE(sum(amount),0) INTO ledger_balance FROM ledger_entries WHERE account_id=checked_account;
  IF stored_balance <> ledger_balance THEN
    RAISE EXCEPTION 'Account balance must match its complete ledger history.';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS balance_reconciliation ON savings_accounts;
CREATE CONSTRAINT TRIGGER balance_reconciliation AFTER INSERT OR UPDATE ON savings_accounts
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION check_account_reconciliation();
DROP TRIGGER IF EXISTS ledger_reconciliation ON ledger_entries;
CREATE CONSTRAINT TRIGGER ledger_reconciliation AFTER INSERT ON ledger_entries
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION check_account_reconciliation();

CREATE OR REPLACE FUNCTION check_transfer_conservation() RETURNS TRIGGER AS $$
DECLARE
  entry_count INTEGER;
  net_amount NUMERIC(14,2);
BEGIN
  IF NEW.type = 'transfer' THEN
    SELECT count(*),COALESCE(sum(amount),0) INTO entry_count,net_amount
      FROM ledger_entries WHERE operation_id=NEW.id;
    IF entry_count <> 2 OR net_amount <> 0 THEN
      RAISE EXCEPTION 'A transfer must have two opposite ledger entries.';
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS transfer_conservation ON money_operations;
CREATE CONSTRAINT TRIGGER transfer_conservation AFTER INSERT ON money_operations
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION check_transfer_conservation();

-- One readable reporting view avoids duplicating the joint-owner join in reports.
CREATE OR REPLACE VIEW account_summary AS
SELECT a.*, r.annual_rate, b.name AS branch_name,
  COALESCE(string_agg(c.full_name, ', ' ORDER BY c.id),'') AS owner_names,
  array_agg(c.id ORDER BY c.id) FILTER (WHERE c.id IS NOT NULL) AS owner_ids,
  min(c.id) AS customer_id,
  min(c.full_name) AS customer_name
FROM savings_accounts a JOIN rates r ON r.id=a.rate_id
JOIN branches b ON b.id=a.branch_id
LEFT JOIN customer_accounts ca ON ca.account_id=a.id
LEFT JOIN customers c ON c.id=ca.customer_id
GROUP BY a.id,r.annual_rate,b.name;

CREATE OR REPLACE VIEW branch_performance AS
SELECT b.id,b.name,b.code,
 (SELECT count(*)::integer FROM customers c WHERE c.branch_id=b.id AND c.status='active') AS active_customers,
 (SELECT count(*)::integer FROM savings_accounts a WHERE a.branch_id=b.id AND a.status='active') AS active_accounts,
 COALESCE((SELECT sum(balance) FROM savings_accounts a WHERE a.branch_id=b.id AND a.status='active'),0) AS savings_balance,
 COALESCE((SELECT sum(f.principal) FROM fixed_deposits f JOIN savings_accounts a ON a.id=f.source_account_id
   WHERE a.branch_id=b.id AND f.status='active'),0) AS fixed_deposit_balance
FROM branches b;
